# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangbanggoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stum',
            name='id',
        ),
        migrations.AlterField(
            model_name='stum',
            name='stuid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
