# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangbanggoapp', '0002_auto_20170809_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='stum',
            name='password',
            field=models.CharField(default=123456, max_length=11, verbose_name='\u5bc6\u7801'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stum',
            name='address',
            field=models.CharField(max_length=40, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='stum',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='stum',
            name='phonenum',
            field=models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='stum',
            name='sex',
            field=models.CharField(max_length=2, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='stum',
            name='stuid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='\u5b66\u53f7'),
        ),
    ]
