# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangbanggoapp', '0003_auto_20170827_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stum',
            name='sex',
        ),
    ]
