# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangbanggoapp', '0004_remove_stum_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30, verbose_name='\u6536\u4ef6\u4eba\u59d3\u540d:')),
                ('saddress', models.CharField(choices=[('x1', '\u884c\u5efa\u8f69\u4e00\u680b'), ('x2', '\u884c\u5efa\u8f69\u4e8c\u680b'), ('x3', '\u884c\u5efa\u8f69\u4e09\u680b'), ('x4', '\u884c\u5efa\u8f69\u56db\u680b'), ('x5', '\u884c\u5efa\u8f69\u4e94\u680b'), ('x6', '\u884c\u5efa\u8f69\u516d\u680b'), ('z1', '\u81f3\u8bda\u8f69\u4e00\u680b'), ('z2', '\u81f3\u8bda\u8f69\u4e8c\u680b'), ('z3', '\u81f3\u8bda\u8f69\u4e09\u680b'), ('z4', '\u81f3\u8bda\u8f69\u56db\u680b'), ('h1', '\u5f18\u6bc5\u8f69\u4e00\u680b'), ('h2', '\u5f18\u6bc5\u8f69\u4e8c\u680b'), ('h3', '\u5f18\u6bc5\u8f69\u4e09\u680b'), ('h4', '\u5f18\u6bc5\u8f69\u56db\u680b'), ('mx', '\u654f\u884c\u8f69')], max_length=2, verbose_name='\u4f4f\u5740:')),
                ('sexpressad', models.CharField(max_length=30, verbose_name='\u5feb\u9012\u540d\u79f0:')),
                ('sename', models.CharField(max_length=15, verbose_name='\u63d0\u53d6\u7801:')),
                ('sphone', models.CharField(default='\u5982:\u624b\u673a\u53f7\u7801\u6216QQ\u53f7', max_length=11, verbose_name='\u8054\u7cfb\u65b9\u5f0f:')),
                ('setype', models.CharField(choices=[('fs', '\u670d\u9970'), ('jj', '\u5bb6\u5177'), ('dq', '\u7535\u5668'), ('mz', '\u7f8e\u5986\u62a4\u80a4'), ('ts', '\u56fe\u4e66'), ('lx', '\u65c5\u884c')], default='\u53ef\u4ee5\u5e2e\u60a8\u63a8\u8350\u597d\u7269\u54e6', max_length=2, verbose_name='\u5feb\u9012\u7c7b\u578b:')),
            ],
        ),
    ]
