# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangbanggoapp', '0005_sendpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendpackage',
            name='setype',
            field=models.CharField(choices=[('fs', '\u670d\u9970'), ('jj', '\u5bb6\u5177'), ('dq', '\u7535\u5668'), ('mz', '\u7f8e\u5986\u62a4\u80a4'), ('ts', '\u56fe\u4e66'), ('lx', '\u65c5\u884c')], default='\u670d\u9970', max_length=2, verbose_name='\u5feb\u9012\u7c7b\u578b:'),
        ),
        migrations.AlterUniqueTogether(
            name='sendpackage',
            unique_together=set([('sname', 'saddress', 'sexpressad', 'sename', 'sphone', 'setype')]),
        ),
    ]
