# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangbanggoapp', '0009_auto_20171118_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendpackage',
            name='saddress',
            field=models.CharField(choices=[('x1', '\u884c\u5efa\u8f69\u4e00\u680b'), ('x2', '\u884c\u5efa\u8f69\u4e8c\u680b'), ('x3', '\u884c\u5efa\u8f69\u4e09\u680b'), ('x4', '\u884c\u5efa\u8f69\u56db\u680b'), ('x5', '\u884c\u5efa\u8f69\u4e94\u680b'), ('x6', '\u884c\u5efa\u8f69\u516d\u680b'), ('z1', '\u81f3\u8bda\u8f69\u4e00\u680b'), ('z2', '\u81f3\u8bda\u8f69\u4e8c\u680b'), ('z3', '\u81f3\u8bda\u8f69\u4e09\u680b'), ('z4', '\u81f3\u8bda\u8f69\u56db\u680b'), ('h1', '\u5f18\u6bc5\u8f69\u4e00\u680b'), ('h2', '\u5f18\u6bc5\u8f69\u4e8c\u680b'), ('h3', '\u5f18\u6bc5\u8f69\u4e09\u680b'), ('h4', '\u5f18\u6bc5\u8f69\u56db\u680b'), ('mx', '\u654f\u884c\u8f69')], max_length=10, verbose_name='\u4f4f\u5740:'),
        ),
        migrations.AlterField(
            model_name='sendpackage',
            name='sphone',
            field=models.CharField(max_length=11, verbose_name='\u8054\u7cfb\u65b9\u5f0f:'),
        ),
    ]
