# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangbanggoapp', '0010_auto_20171118_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendpackage',
            name='saddress',
            field=models.CharField(choices=[('\u884c\u5efa\u8f69\u4e00\u680b', '\u884c\u5efa\u8f69\u4e00\u680b'), ('\u884c\u5efa\u8f69\u4e8c\u680b', '\u884c\u5efa\u8f69\u4e8c\u680b'), ('\u884c\u5efa\u8f69\u4e09\u680b', '\u884c\u5efa\u8f69\u4e09\u680b'), ('\u884c\u5efa\u8f69\u56db\u680b', '\u884c\u5efa\u8f69\u56db\u680b'), ('\u884c\u5efa\u8f69\u4e94\u680b', '\u884c\u5efa\u8f69\u4e94\u680b'), ('\u884c\u5efa\u8f69\u516d\u680b', '\u884c\u5efa\u8f69\u516d\u680b'), ('\u81f3\u8bda\u8f69\u4e00\u680b', '\u81f3\u8bda\u8f69\u4e00\u680b'), ('\u81f3\u8bda\u8f69\u4e8c\u680b', '\u81f3\u8bda\u8f69\u4e8c\u680b'), ('\u81f3\u8bda\u8f69\u4e09\u680b', '\u81f3\u8bda\u8f69\u4e09\u680b'), ('\u81f3\u8bda\u8f69\u56db\u680b', '\u81f3\u8bda\u8f69\u56db\u680b'), ('\u5f18\u6bc5\u8f69\u4e00\u680b', '\u5f18\u6bc5\u8f69\u4e00\u680b'), ('\u5f18\u6bc5\u8f69\u4e8c\u680b', '\u5f18\u6bc5\u8f69\u4e8c\u680b'), ('\u5f18\u6bc5\u8f69\u4e09\u680b', '\u5f18\u6bc5\u8f69\u4e09\u680b'), ('\u5f18\u6bc5\u8f69\u56db\u680b', '\u5f18\u6bc5\u8f69\u56db\u680b'), ('\u654f\u884c\u8f69', '\u654f\u884c\u8f69')], max_length=10, verbose_name='\u4f4f\u5740:'),
        ),
    ]
