# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangbanggoapp', '0012_stum_stuscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendpackage',
            name='stuid',
            field=models.CharField(default=201550080508, max_length=12, verbose_name='\u5b66\u53f7'),
            preserve_default=False,
        ),
    ]
