# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangbanggoapp', '0013_sendpackage_stuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendpackage',
            name='sflag',
            field=models.IntegerField(default=0, verbose_name='\u662f\u5426\u63a5\u5355:'),
        ),
    ]
